info:
  version: @project.version@

spring:
  application:
    name: JMX-Client
    index: 1
  boot:
    admin:
      url: http://localhost:8090
  redis:
    host: localhost
    port: 6379
    password:
    pool:
      max-active: 10
      max-wait: 1000
#  datasource:
#    url: jdbc:oracle:thin:@192.168.233.241:1521:orcl
#    username: spdb
#    password: cmiot
#  jmx:
#    default-domain: com.baron.actuator.jmx
#    enabled: true
server:
  port: 8082

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.index}:${random.value}
    prefer-ip-address: true
    hostname: jmx-client-${spring.application.index}
    status-page-url-path: ${management.context-path}/info
    health-check-url-path: ${management.context-path}/health
    metadata-map:
      management:
        context-path: ${management.context-path}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
management:
  security:
    enabled: false
  context-path: /manage


